---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/sign_in":
    post:
      summary: Sign_in User
      tags:
      - Sessions
      parameters:
      - name: auth
        in: header
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Logged user
          content: {}
  "/api/v1/auth/sign_out":
    delete:
      summary: Sign_out User
      tags:
      - Sessions
      parameters:
      - name: auth
        in: header
        schema:
          type: object
          properties:
            access-token:
              type: string
            client:
              type: string
            uid:
              type: string
      responses:
        '200':
          description: Sign-out User
          content: {}
  "/api/v1/users":
    get:
      summary: List Users
      tags:
      - Users
      responses:
        '200':
          description: Listing Users
          content: {}
    post:
      summary: Create an User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: integer
              required:
              - first_name
              - last_name
              - email
              - password
              - role
  "/api/v1/users/{id}":
    get:
      summary: Show an User
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user show
          content: {}
        '404':
          description: not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
    patch:
      summary: Update an User
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user updated
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: integer
              required:
              - first_name
              - last_name
              - email
              - password
    delete:
      summary: Delete an User
      tags:
      - Users
      parameters: []
      responses:
        '204':
          description: no_content
          content: {}
        '404':
          description: not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
              - id
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
